### ISSUE TITLE
Bump supported version of Pydantic

### ISSUE THREAD

**Issue by edgarrmondragon** [quantile-development/dagster-ext#14]
Dagster 1.9 requires Pydantic `>=2,<2.10`, but this package depends on Pydantic `>=1.9.0,<2.0.0`:

https://github.com/quantile-development/dagster-ext/blob/d56102022fe269654b6f03e633b9856dbc69a0ea/pyproject.toml#L31

Is it possible to bump the supported version? Maybe even remove the upper constraint entirely?

Thanks!

Ref:

- Slack thread: https://meltano.slack.com/archives/C069CQNHDNF/p1730485067579339

**Comment by joshua-janicas** [comment]
https://github.com/quantile-development/dagster-ext/pull/15

@JulesHuisman  would you be able to take a look! Thank you!
