### ISSUE TITLE
Create several schedules with same job and different env

### ISSUE THREAD

**Issue by Volna13** [quantile-development/dagster-ext#3]
When I create many schedules(with save job) inside dagster I only see the last one described.
<img width="1189" alt="image" src="https://user-images.githubusercontent.com/49818336/208903173-a36c5dd2-b0a6-4702-9d37-a67f85cf92a1.png">
![image](https://user-images.githubusercontent.com/49818336/208903213-b87de69f-59fa-41d9-9f0b-c0400fd13744.png)

**Comment by JulesHuisman** [comment]
@Volna13 If you install the latest version there should be support for multiple schedules per job.
