### ISSUE TITLE
Invoke with daemon (like 'dagster dev' command)

### ISSUE THREAD

**Issue by acarter24** [quantile-development/dagster-ext#7]
Not 100% sure of this, so apologies if I am incorrect. It looks like the `meltano invoke dagster:start` command starts dagster but without any scheduling daemon.

Is it possible to have an option to invoke with `dagster dev` to get the scheduler too?

**Comment by JulesHuisman** [comment]
That is a good idea! This probably wouldn't be a big change to do.

**Comment by acarter24** [comment]
Thanks. I've since managed to get dagster to start meltano using your excellent `dagster_meltano` library, rather than getting meltano to start dagster as a utility. All a bit confusing at first :)

**Comment by JulesHuisman** [comment]
Yeah, it's a bit of an inception for now. But glad you got it working!
